### ISSUE TITLE
Missing templates

### ISSUE THREAD

**Issue by jordij** [rkhleics/wagtailmodeladmin#25]
My installation of 2.0.5 works fine but the `templates` folder is not included in the installation. Below you can see the output of running `ls -la` in the installed package folder. As you can see the folder is missing.

<img width="871" alt="screen shot 2015-11-18 at 4 10 25 pm" src="https://cloud.githubusercontent.com/assets/3124220/11231582/ffedc230-8e0e-11e5-8b30-b1b8e451f260.png">

Might well be related to https://github.com/ababic/wagtailmodeladmin/issues/24

**Comment by ababic** [comment]
Sorry! When packaging for pip, it created a new MANIFEST file, which I'd never seen before, and so didn't add into the repo. The latest version should install fine now.

**Comment by jordij** [comment]
No worries, thanks for the quick fix!

**Comment by alexgleason** [comment]
Still having this problem when installing with `pip install wagtailmodeladmin`. It says 2.0.8

I installed `pip install https://github.com/ababic/wagtailmodeladmin.git` and that worked.

**Comment by ababic** [comment]
Ahh, damn :( If you install version 2.0.7 for now, that should work. I'll
have the latest version sorted today.

**Comment by ababic** [comment]
Looks like it's working again now! The latest version is `2.1.1`.

**Comment by cubicuboctahedron** [comment]
@ababic there is no ```templates``` directory in ```2.1.1``` for me. Everything works fine with ```pip install git+https://github.com/ababic/wagtailmodeladmin.git``` though.

**Comment by ababic** [comment]
@cubicuboctahedron Thanks for letting me know. Have tested on a fresh virtualenv and `2.1.2` has installed correctly and seems to be working. 

I can't begin to explain how frustrating all this MANIFEST / PyPi business is for me. I'm sure it's simple to a lot of people, but It's totally out of my skill set.

**Comment by alexgleason** [comment]
Thank you! This extension has been really helpful! :smile:

**Comment by alexgleason** [comment]
Still not working for me unfortunately.

```
[pedsnet vagrant]$ pip show wagtailmodeladmin
---
Metadata-Version: 2.0
Name: wagtailmodeladmin
Version: 2.1.2
Summary: Customisable 'django-admin' style listing pages for Wagtail
Home-page: https://github.com/ababic/wagtailmodeladmin
Author: Andy Babic
Author-email: ababic@rkh.co.uk
License: MIT
Location: /home/vagrant/.virtualenvs/pedsnet/lib/python3.4/site-packages
Requires: wagtail, Django
[pedsnet vagrant]$ ls /home/vagrant/.virtualenvs/pedsnet/lib/python3.4/site-packages/wagtailmodeladmin/
forms.py     menus.py       options.py             __pycache__   utils.py
__init__.py  middleware.py  permission_helpers.py  templatetags  views.py
[pedsnet vagrant]$ 
```

As you can see there's no `templates` directory.

**Comment by ababic** [comment]
I don't know how I missed that. Sorry. Please try one more time (2.1.3)

**Comment by alexgleason** [comment]
It works. :smile: Thank you!

**Comment by ababic** [comment]
Is anyone else seeing this issue with the latest pip-installable version? 

If so, please pip install the github version for now, until we can find a fix:
`pip install git+https://github.com/ababic/wagtailmodeladmin.git`

**Comment by kingel** [comment]
i strongly recommend using:
https://pypi.python.org/pypi/check-manifest/
https://pypi.python.org/pypi/zest.releaser

to release to pypi

**Comment by ababic** [comment]
Thanks @kingel. I'll check out zest when I have time. Updated setuptools to the latest version, redistributed,  and it seems to be fine again for the timebeing.
