### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by shulcsm** [rkhleics/wagtailmodeladmin#30]

**Comment by shulcsm** [comment]
I removed pinned version and everything seems to be working. I'm not sure why it's pinned to concrete django version, pinning wagtail should be enough.

**Comment by shulcsm** [comment]
nvm, it may require some work. I forked for now, let me know how you want to handle compatibility.

**Comment by ababic** [comment]
Hi @shulcsm. If you need 1.9 compatibility immediately, you may want to check out the 2.2 branch here, as there are some Django 1.9 compatibility fixes in there already. I'm waiting for some time after the holidays until I can sit down and confirm things are working before merging it all in. 

RE the pinning of Django version: wagtailmodeladmin utilises a lot of things from Django (particularly contrib.admin), which are subject to change accross minor and major versions, so pinning that is kind of necessary to keep things working reliably.

**Comment by ababic** [comment]
FYI, we're currently working with torchbox on a pull request to get wagtailmodeladmin into the wagtail project as a contrib app for version 1.4: https://github.com/torchbox/wagtail/pull/1829

**Comment by shulcsm** [comment]
Great, thanks.
