### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by mixxorz** [rkhleics/wagtailmodeladmin#31]
Are there any compatibility issues with Django 1.9? Wagtail 1.3 was released recently, and it's fully compatible with Django 1.9.

If there aren't any issues, I think we should remove the `django<1.9` requirement in `setup.py`.

**Comment by ababic** [comment]
There are a few compatibility issues with Django 1.9. As far as I know, the following commit on the 2.2 branch is enough to get things running again, but i'm struggling to test fully, as I have other commitments:
https://github.com/rkhleics/wagtailmodeladmin/commit/57aa41e3131c3de52d3617819a606cb2cdfab1aa

If anybody is able to test the above and confirm compatibility, I'll be happy to patch the master branch and remove that requirement. If not, wagtailmodeladmin should be available as a contrib app in wagtail come version 1.4, where 1.9 support will definitely be fixed.

**Comment by mixxorz** [comment]
I updated to the 2.2 branch. All seems well so far.

**Comment by ababic** [comment]
Have merged everything into the master branch now

**Comment by mixxorz** [comment]
This is awesome. Thanks a lot!
