### ISSUE TITLE
Admin form missing enctype

### ISSUE THREAD

**Issue by nkuttler** [rkhleics/wagtailmodeladmin#37]
I have a simple Model with an ImageField, but the generated admin form doesn't have enctype="multipart/form-data", so the file is never received. I realize I could just override the template, but it seems like this should be the default behavior of the app, or should at least be configurable?

**Comment by ababic** [comment]
Hi @nkuttler. The create/edit templates in this project were, for the most part, simply copied from the wagtailsnippets app within wagtail itself, where the `enctype` attribute isn't present on the form either. I guess the thinking behind it is that images and documents should all be handled via the built-in image and document libraries - negating the need for `FileField` or `ImageField` all together. However, I can certainly understand why that might not fit every developer's use case.

I can't claim to know the full effect that blanket use of enctype="multipart/form-data" would have, but I don't like the idea of using it unless it is needed. Having looked at the way Django itself has gone about solving the same problem, it seems that they felt the same way too (https://github.com/django/django/blob/3541ca1504d75b6b4fc8b8db0e7d62e990433f12/django/contrib/admin/options.py#L1042), but have yet to implement something to do the working out.

I'll have a think.
