### ISSUE TITLE
error Unable to lookup 't'

### ISSUE THREAD

**Issue by stefaniadem** [rkhleics/wagtailmodeladmin#39]
Hi,
 This is the error I get when I create an object in my snippet. error Unable to lookup 't'.
If I cooment this line in wagtailmdeladmin/templates/index.html line 70 {% result_list view object_list %} it works but obviously objectlist do not show up. Any Idea?

**Comment by ababic** [comment]
Hi @stefaniadem. Check `list_display` on your ModelAdmin class. Sounds like you're providing a string value, rather than a list of tuple (tuples need a comma in there somewhere).

**Comment by stefaniadem** [comment]
Wonderful!!!  Now it works.
Thanks a lot!
