### ISSUE TITLE
Wrong form filed types redering

### ISSUE THREAD

**Issue by SalahAdDin** [rkhleics/wagtailmodeladmin#41]
I man,

I saw a small wrong with template redering:
![seleccion_004](https://cloud.githubusercontent.com/assets/5034215/13198777/ffc6fc02-d7df-11e5-910c-af0d3ce03e55.png)

The second input have't styles, but the other have it.

In addion:
![seleccion_006](https://cloud.githubusercontent.com/assets/5034215/13198786/2ad9a9e4-d7e0-11e5-960d-0dd3d20278b2.png)

Filter input types haven't styles.

Thanks!

**Comment by ababic** [comment]
Hi Yusuf.

The only form-related styles used in this package are on the 'choose
parent' page... everything else uses stock wagtail styles. I've got no idea
what's causing your form to look that way. It could be another package, or
maybe a browser plugin, but I'm quite certain this package isn't the
problem.

**Comment by SalahAdDin** [comment]
Ok, yes, for form input field is a problem with the package, but, in the filter, i don't know what happen, can you show me how should be see?

**Comment by ababic** [comment]
Hi @SalahAdDin. Are you using django-suit in your set up, by any chance? The filters, specifically, rely on django admin code for definition and rendering... it seems like django-suit is somehow interfering with that.

For reference, here's how things should look:

![Imgur](http://i.imgur.com/2OK9MXb.png)

**Comment by SalahAdDin** [comment]
No, i'm not using it, i'm using django yet, but, should be the same error. Ok, my problem its filder, but, maybe i cand solve it. Thanks!
