### ISSUE TITLE
Filtering doesn't work due to missing Javascript hook

### ISSUE THREAD

**Issue by coredumperror** [rkhleics/wagtailmodeladmin#42]
I just discovered this plugin, and I can already tell I'm going to love it. The lack of this kind of functionality was initially a major blow against Wagtail's viability for my code shop's purposes.

Setup was easy, and the search functionality seems to work fine, but the Filter isn't working for some reason. 

```
from wagtailmodeladmin.options import ModelAdmin, wagtailmodeladmin_register, ModelAdminGroup
from .models import StaticPage


class StaticPageModelAdmin(ModelAdmin):
    model = StaticPage
    menu_icon = 'doc-empty'
    menu_order = 200
    add_to_settings_menu = False
    list_display = ['title', 'live']
    list_filter = ['live']
    search_fields = ['title']


class MyModelAdminGroup(ModelAdminGroup):
    menu_label = 'Core Models'
    menu_icon = 'folder-open-inverse'
    menu_order = 200 # Put this element 3rd in the sidebar (000 being first, 100 second, etc.)
    items = [StaticPageModelAdmin]


wagtailmodeladmin_register(MyModelAdminGroup)
```

I can see the listing page just fine, the checkboxes appear correctly for live and non-live pages, but the Filter dropdown has no affect at all. I can set it to "Yes", "No", "---", or "Live", and nothing happens, even when there are some live and some non-live Static Pages.

I'll look into the code to see if I can find the culprit.

**Comment by coredumperror** [comment]
I think I know the source of the problem, but I haven't been able to determine the solution. The issue is that there's no javascript hooked into the "change" event on the Filter dropdown. There is JS hooked into that if you look at a filterable listing in the normal Django admin, but I'm not sure which js file is supposed to be included to make it work. Or how to include said file.

I did discover that if you manually set the URL to `http://example.com:8000/admin/modeladmin/core/staticpage/?live=`, you'll get only non-live pages. And using `live=yes` (or any other value) will give only Live pages.

**Comment by ababic** [comment]
Hey @coredumperror. Glad to hear you're finding the plugin useful! Sorry to hear you've been having some trouble, though. Any chance you can share a pip freeze of your current environment? 

The filters are supposed to render as simple lists of links with the correct links on, and not dropdowns... which would explain why they're not working for you. The rendering of the filters is passed on to a bit of django admin code though, so I wonder if there's some complication with that?

**Comment by coredumperror** [comment]
Huh, I hadn't thought of that. Perhaps it's because I'm using django-suit? Here's my pip freeze:
```
appnope==0.1.0
beautifulsoup4==4.4.1
boto==2.39.0
decorator==4.0.9
Django==1.9.2
django-appconf==1.0.1
django-braces==1.8.1
django-compressor==2.0
django-extensions==1.6.1
django-js-reverse==0.6.1
django-model-utils==2.4
django-modelcluster==1.1
django-settings-export==1.0.6
django-storages==1.4
django-suit==0.2.16
django-suit-ckeditor==0.0.2
django-taggit==0.18.0
django-treebeard==3.0
djangorestframework==3.3.2
docutils==0.12
factory-boy==2.6.1
fake-factory==0.5.3
funcsigs==0.4
gnureadline==6.3.3
gunicorn==19.4.5
html5lib==0.9999999
ipython==4.1.1
ipython-genutils==0.1.0
mock==1.3.0
MySQL-python==1.2.5
path.py==8.1.2
pbr==1.8.1
pexpect==4.0.1
pickleshare==0.6
Pillow==3.1.1
ptyprocess==0.5.1
python-dateutil==2.4.2
python-memcached==1.57
pytz==2015.7
rcssmin==1.0.6
rebar==0.1
rjsmin==1.0.12
simplegeneric==0.8.1
six==1.10.0
suit==2.0.2
testfixtures==4.8.0
traitlets==4.1.0
Unidecode==0.4.19
wagtail==1.3.1
wagtailmodeladmin==2.3.5
wheel==0.24.0
Willow==0.2.2
```

I'll try disabling django-suit to see what happens.

**Comment by coredumperror** [comment]
Yup, that did it. Looks like suit is getting some (but not all) of its hook into whatever django admin code you're using. My code shop's been using suit for so long that I completely forgot that it's not the default django admin. 

Now I gotta figure out how to either make it stop hooking into wagtailmodeladmin, or start hooking all the way into it. That sounds daunting...

**Comment by ababic** [comment]
Damn, that might explain some issues another guy was having, too :P Thanks for digging! If you were going to find a fix, I think your best bet would be to look at the `get_filters` method on `wagtailmodeladmin.views.IndexView`... specifically the stuff using `django.contrib.admin.FieldListFilter`... it seems to be FieldListFilter that sets some kind of template for rendering.

**Comment by ababic** [comment]
I built this app to be really easy to extend, so you should be able to easily sub-class `wagtailmodeladmin.views.IndexView` to create a custom one, then hook it up to you ModelAdmin class like so:

```
class StaticPageModelAdmin(ModelAdmin):
    model = StaticPage
    index_view_class = MyCustomIndexView
```

**Comment by coredumperror** [comment]
Cool, I'll give that a shot after lunch.

**Comment by ababic** [comment]
So, did some digging myself and here's the template that should be rendering the filters:
https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/filter.html

Suit seems to be overriding that with this:
https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/filter.html

The django docs on `list_filter` mention something about subclassing `FieldListFilter` and setting a `template` variable on it to override: https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter

So, I guess just recreate the original template somewhere, subclass `django.contrib.admin.FieldListFilter` and make it use that template... then override `get_filters` on you custom IndexView to use you custom `FieldListFilter` class instead of the django one.... simple :)

**Comment by ababic** [comment]
I've just made life a little easier for you, by adding the `flf_class` attribute to IndexView. You can now just override that to use your custom `FieldListFilter` class in `get_filters`, instead of having to rewrite that method.

**Comment by coredumperror** [comment]
Boy oh boy, the process of making this work was a real doozey. I couldn't just use your `flf_class` and then override the `template` class variable on my custom `FieldListFilter` subclass, because the `FieldListFilter` class isn't actually used directly to render the fields. The individual subclasses of `FieldListFilter`, like `BooleanFieldListFilter`, are the ones that actually have their `template` attribute used.

At first I tried adding a priority registration of a custom sublclass of `BooleanFieldListFilter`, but I realized that would also change how the filter is rendered within Suit, which I didn't want to do. The method I came up with only changes the template name for `FieldListFilter`s that are rendered through my `StaticPageModelAdmin` class.

To make this work, I had to override `FieldListFilter.create()` in my `flf_class`, and have it create a new class on-the-fly as it looped through `FieldListFilter`'s listing of its registered subclasses. That new class overrides the `template` name, which makes it work.

```
from wagtailmodeladmin.options import ModelAdmin, wagtailmodeladmin_register, ModelAdminGroup
from wagtailmodeladmin.views import IndexView
from django.contrib.admin.filters import FieldListFilter
from .models import StaticPage

class SuitCompatibleFieldListFilter(FieldListFilter):

    @classmethod
    def create(cls, field, request, params, model, model_admin, field_path):
        for test, list_filter_class in cls._field_list_filters:
            if not test(field):
                continue

            class SuitCompatibleListFilterSubclass(list_filter_class):
                template = 'core/filter.html'

            return SuitCompatibleListFilterSubclass(
                field, request, params, model, model_admin, field_path=field_path
            )

class SuitCompatibleIndexView(IndexView):
    flf_class = SuitCompatibleFieldListFilter

class StaticPageModelAdmin(ModelAdmin):
    model = StaticPage
    menu_icon = 'doc-empty'
    menu_order = 000
    add_to_settings_menu = False
    list_display = ['title', 'live']
    list_filter = ['live']
    search_fields = ['title']
    index_view_class = SuitCompatibleIndexView

class CoreModelsAdminGroup(ModelAdminGroup):
    menu_label = 'Core Content Types'
    menu_icon = 'folder-open-inverse'
    menu_order = 200 # Put this element 3rd in the sidebar (000 being first, 100 second, etc.)
    items = [StaticPageModelAdmin]

wagtailmodeladmin_register(CoreModelsAdminGroup)
```

`core` is the name of the app I have this code in, which is where `'core/filter.html'` comes from.

If you want to build this into wagtailmodeladmin, you could set `IndexView.flf_class` to a class like `SuitCompatibleFieldListFilter`, and have it use your own copy of `filter.html` copied from `django.contrib.admin`. It's possible that this would be a good idea for other templates, too, though I personally haven't run into any other incompatibilities with Suit.

**Comment by ababic** [comment]
Hey @coredumperror. Sorry it wasn't easy as first thought, there's not a lot about Django admin that's simple :) I think we've both learned that the hard way.

With this all in mind, I think it's going to be better to tackle this from the rendering/templatetag side of things instead. Will have a think!

**Comment by coredumperror** [comment]
So if I'm reading this commit right, you cut out the django admin code for rendering the filter list, and started rendering it entirely within wagtailmodeladmin, instead? If so, that sounds like a much better solution.

**Comment by ababic** [comment]
Yeah, that's about the shape of it. The django admin filter was really very simple, so I didn't mind recreating it.
