### ISSUE TITLE
modify index template?

### ISSUE THREAD

**Issue by gauteh** [rkhleics/wagtailmodeladmin#45]
Hi,

I would like to modify the index template for my model, is that possible? Specifically I want to add some more general stats about my custom models at the top of the list of entries.

Thanks for this, it is great!

**Comment by ababic** [comment]
Hi @gauteh. Yes, certainly. You have a few options for this. The easiest is to put your template in a preferred location, and have it picked up automatically. Either of these would work:

- wagtailmodeladmin/appname/modelname/index.html 
- wagtailmodeladmin/appname/index.html

Or you can set the `index_template_name` attribute on your ModelAdmin class to specify a different location.

**Comment by gauteh** [comment]
great, thanks!

Andy Babic writes on March 13, 2016 23:09:
