### ISSUE TITLE
Addition action on foreign key fields, like in Django Admin

### ISSUE THREAD

**Issue by paul-apacio** [rkhleics/wagtailmodeladmin#51]
This is a great plugin.

I was wondering if you could add in a create new action next to foreign key fields much like in the standard Django Admin?

**Comment by ababic** [comment]
Hi Paul,

Thanks for your comments. I'm glad you've found the plugin useful.

The actual rendering of fields is all handled by Wagtail, with their preset
edit handlers and accompanying style settings. In the case of pages, they
use Wagtail's page editing views entirely, so there's certainly no way to
control form rendering for those.

As far as I know, there are several similar issues on the wagtail github
project discussing matters such as this. You may want to try and join in
the conversation on those. They've recently assigned a new UI lead to their
dev team, so expect some positive changes in the near future :)
